name: conan-package

on:
  push:
    paths:
      - 'src/**'
      - 'include/**'
      - 'test_package/**'
      - 'tests/**'
      - 'conanfile.py'
      - 'conandata.yml'
      - 'CMakeLists.txt'
      - '.github/workflows/conan-package.yml'
    branches:
      - main
      - master
      - 'CURA-*'
      - 'PP-*'
      - '[0-9].[0-9]*'
      - '[0-9].[0-9][0-9]*'
    tags:
      - '[0-9].[0-9].[0-9]*'
      - '[0-9].[0-9][0-9].[0-9]*'

jobs:
# FIXME: Use main once merged
  conan-package:
    uses: ultimaker/cura-workflows/.github/workflows/conan-package.yml@CURA-11622_conan_v2
    secrets: inherit
