name: unit-test

on:
  push:
    paths:
      - 'src/**'
      - 'include/**'
      - 'test_package/**'
      - 'tests/**'
      - 'cmake/**'
      - 'conanfile.py'
      - 'conandata.yml'
      - 'CMakeLists.txt'
      - '.github/workflows/requirements*'
      - '.github/workflows/unit-test.yml'
    branches:
      - main
      - master
      - 'CURA-*'
      - '[0-9].[0-9]*'
      - '[0-9].[0-9][0-9]*'
    tags:
      - '[0-9].[0-9].[0-9]'
      - '[0-9].[0-9][0-9].[0-9]'
  pull_request:
    paths:
      - 'src/**'
      - 'include/**'
      - 'test_package/**'
      - 'tests/**'
      - 'cmake/**'
      - 'conanfile.py'
      - 'conandata.yml'
      - 'CMakeLists.txt'
      - '.github/workflows/requirements*'
      - '.github/workflows/unit-test.yml'
    branches:
      - main
      - master
      - 'CURA-*'
      - '[0-9].[0-9]*'
      - '[0-9].[0-9][0-9]*'
    tags:
      - '[0-9].[0-9].[0-9]'
      - '[0-9].[0-9][0-9].[0-9]'

jobs:
  testing:
    name: Run unit tests
# FIXME: use main once merged
    uses: ultimaker/cura-workflows/.github/workflows/unit-test.yml@CURA-11622_conan_v2
    with:
      test_use_ctest: true
